### ISSUE TITLE
[suggestion] Create a "Tools" topic

### ISSUE THREAD

**Issue by akz92** [Cap-go/awesome-ionic#6]
Hi, I created a Vim plugin to highlight Ionic 2 html code and I'd like to add it to this list, but I didn't find a topic that fits it. So I'd like to suggest creating a "Tools" topic to keep tools related to development.

**Comment by candelibas** [comment]
Hi!
It would be great.  I've added "Tools" under "i18n & l10n" category. You can do pull request to add it.
